/**
 */
package catalogue.provider;

import catalogue.util.CatalogueAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class CatalogueItemProviderAdapterFactory extends CatalogueAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CatalogueItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Catalogue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CatalogueItemProvider catalogueItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Catalogue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCatalogueAdapter() {
		if (catalogueItemProvider == null) {
			catalogueItemProvider = new CatalogueItemProvider(this);
		}

		return catalogueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Composant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposantItemProvider composantItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Composant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComposantAdapter() {
		if (composantItemProvider == null) {
			composantItemProvider = new ComposantItemProvider(this);
		}

		return composantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.TypeMetadonnee} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeMetadonneeItemProvider typeMetadonneeItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.TypeMetadonnee}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeMetadonneeAdapter() {
		if (typeMetadonneeItemProvider == null) {
			typeMetadonneeItemProvider = new TypeMetadonneeItemProvider(this);
		}

		return typeMetadonneeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Metadonnee} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetadonneeItemProvider metadonneeItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Metadonnee}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetadonneeAdapter() {
		if (metadonneeItemProvider == null) {
			metadonneeItemProvider = new MetadonneeItemProvider(this);
		}

		return metadonneeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Port} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortItemProvider portItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Port}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortAdapter() {
		if (portItemProvider == null) {
			portItemProvider = new PortItemProvider(this);
		}

		return portItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Empreinte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmpreinteItemProvider empreinteItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Empreinte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmpreinteAdapter() {
		if (empreinteItemProvider == null) {
			empreinteItemProvider = new EmpreinteItemProvider(this);
		}

		return empreinteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Et} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EtItemProvider etItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Et}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEtAdapter() {
		if (etItemProvider == null) {
			etItemProvider = new EtItemProvider(this);
		}

		return etItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Ou} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OuItemProvider ouItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Ou}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOuAdapter() {
		if (ouItemProvider == null) {
			ouItemProvider = new OuItemProvider(this);
		}

		return ouItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Non} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NonItemProvider nonItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Non}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNonAdapter() {
		if (nonItemProvider == null) {
			nonItemProvider = new NonItemProvider(this);
		}

		return nonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.Redondance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RedondanceItemProvider redondanceItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.Redondance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRedondanceAdapter() {
		if (redondanceItemProvider == null) {
			redondanceItemProvider = new RedondanceItemProvider(this);
		}

		return redondanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.GeoGenerale} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeoGeneraleItemProvider geoGeneraleItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.GeoGenerale}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeoGeneraleAdapter() {
		if (geoGeneraleItemProvider == null) {
			geoGeneraleItemProvider = new GeoGeneraleItemProvider(this);
		}

		return geoGeneraleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link catalogue.GeoSpecifique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeoSpecifiqueItemProvider geoSpecifiqueItemProvider;

	/**
	 * This creates an adapter for a {@link catalogue.GeoSpecifique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeoSpecifiqueAdapter() {
		if (geoSpecifiqueItemProvider == null) {
			geoSpecifiqueItemProvider = new GeoSpecifiqueItemProvider(this);
		}

		return geoSpecifiqueItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (catalogueItemProvider != null) catalogueItemProvider.dispose();
		if (composantItemProvider != null) composantItemProvider.dispose();
		if (typeMetadonneeItemProvider != null) typeMetadonneeItemProvider.dispose();
		if (metadonneeItemProvider != null) metadonneeItemProvider.dispose();
		if (portItemProvider != null) portItemProvider.dispose();
		if (empreinteItemProvider != null) empreinteItemProvider.dispose();
		if (etItemProvider != null) etItemProvider.dispose();
		if (ouItemProvider != null) ouItemProvider.dispose();
		if (nonItemProvider != null) nonItemProvider.dispose();
		if (redondanceItemProvider != null) redondanceItemProvider.dispose();
		if (geoGeneraleItemProvider != null) geoGeneraleItemProvider.dispose();
		if (geoSpecifiqueItemProvider != null) geoSpecifiqueItemProvider.dispose();
	}

}
