<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="catalogue"
    nsURI="http://www.example.org/catalogue"
    nsPrefix="catalogue">

  <!-- Catalogue -->
  <eClassifiers xsi:type="ecore:EClass" name="Catalogue">
    <eStructuralFeatures xsi:type="ecore:EReference"
        name="components"
        upperBound="-1"
        containment="true"
        eType="#//Component"
        eOpposite="#//Component/catalogue"/>
  </eClassifiers>

  <!-- Component -->
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EString"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="footprint"
        eType="#//Footprint"
        containment="true"
        lowerBound="0"
        upperBound="1"
        eOpposite="#//Footprint/component"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="metadonnees"
        upperBound="-1"
        containment="true"
        eType="#//MetaDonnee"
        eOpposite="#//MetaDonnee/component"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="ports"
        upperBound="-1"
        containment="true"
        eType="#//Port"
        eOpposite="#//Port/component"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="catalogue"
        lowerBound="1"
        eType="#//Catalogue"
        eOpposite="#//Catalogue/components"/>
  </eClassifiers>

  <!-- Footprint -->
  <eClassifiers xsi:type="ecore:EClass" name="Footprint">
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EString"/>

    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="width"
        eType="ecore:EDouble"/>

    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="height"
        eType="ecore:EDouble"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="pads"
        upperBound="-1"
        containment="true"
        eType="#//Pad"
        eOpposite="#//Pad/footprint"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="component"
        lowerBound="0"
        upperBound="1"
        eType="#//Component"
        eOpposite="#//Component/footprint"/>
  </eClassifiers>

  <!-- Pad -->
  <eClassifiers xsi:type="ecore:EClass" name="Pad">
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="x"
        eType="ecore:EDouble"/>

    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="y"
        eType="ecore:EDouble"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="port"
        lowerBound="0"
        upperBound="1"
        eType="#//Port"
        eOpposite="#//Port/pads"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="footprint"
        lowerBound="1"
        eType="#//Footprint"
        eOpposite="#//Footprint/pads"/>
  </eClassifiers>

  <!-- Port -->
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EString"/>

    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="direction"
        eType="#//DirectionPort"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="pads"
        upperBound="-1"
        eType="#//Pad"
        eOpposite="#//Pad/port"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="component"
        lowerBound="1"
        eType="#//Component"
        eOpposite="#//Component/ports"/>
  </eClassifiers>

  <!-- MetaDonnee -->
  <eClassifiers xsi:type="ecore:EClass" name="MetaDonnee">
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EString"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="type"
        lowerBound="1"
        eType="#//TypeMetaDonnee"
        eOpposite="#//TypeMetaDonnee/metadonnees"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="component"
        lowerBound="1"
        eType="#//Component"
        eOpposite="#//Component/metadonnees"/>
  </eClassifiers>

  <!-- TypeMetaDonnee -->
  <eClassifiers xsi:type="ecore:EClass" name="TypeMetaDonnee">
    <eStructuralFeatures xsi:type="ecore:EAttribute"
        name="key"
        eType="ecore:EString"/>

    <eStructuralFeatures xsi:type="ecore:EReference"
        name="metadonnees"
        upperBound="-1"
        eType="#//MetaDonnee"
        eOpposite="#//MetaDonnee/type"/>
  </eClassifiers>

  <!-- Enum -->
  <eClassifiers xsi:type="ecore:EEnum" name="DirectionPort">
    <eLiterals name="IN"/>
    <eLiterals name="OUT"/>
    <eLiterals name="INOUT"/>
  </eClassifiers>

</ecore:EPackage>
